pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = " "
        PROJECT = "roboshop"
    }
    options {
        timeout(time:30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // Build
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 00-vpc
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        
        post {
            always {
                echo 'I will always say Hello again!'
                deleteDir()
            }
            success {
                echo 'Hello Success'
            }
            failure {
                echo 'Hello Failure'
            }
        }
    }
}