pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "632745187858 "
        PROJECT = "roboshop"
    }
    options {
        timeout(time:30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // Build
    stages {
        stage('Init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: env.REGION) {
                        dir('00-vpc') {
                            sh "terraform init -reconfigure"
                        }
                    }
                }
            }
        }
    }
    stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 00-vpc
                            terraform plan
                        """                    
                    }
                }
            }
        }
        stage('apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 00-vpc
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success {
            echo 'Hello Success'
        }
        failure {
            echo 'Hello Failure'
        }
    }
}