pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "632745187858 "
        PROJECT = "roboshop"
    }
    options {
        timeout(time:30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // Build
    stages {
        stage('Init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: env.REGION) {
                        dir('00-vpc') {
                            sh "terraform init -reconfigure"
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success {
            echo 'Hello Success'
        }
        failure {
            echo 'Hello Failure'
        }
    }
}